# This job listens for new releases and will build the appropriate artifacts
# and upload them to the release.

name: Release

on:
  release:
    types: [published]

jobs:
  build-upload:
    runs-on: ubuntu-latest
    permissions:
      # For flakehub cache
      id-token: write
      # For artifact upload
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: DeterminateSystems/nix-installer-action@v16
      with:
        determinate: true
    - uses: DeterminateSystems/flakehub-cache-action@04eb56b73c2de9e098015ec61db998329962ed34
    - name: Build artifacts
      run: nix develop --command bash -c "OUT=./assets ./scripts/create-assets.sh"

    - name: Upload artifacts
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release upload ${{ github.ref_name }} ./assets/*
